import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { resend } from "@/lib/resend";
import { render } from "@react-email/render";
import NewsletterWelcomeEmail from "@/emails/NewsletterWelcomeEmail";
import NewsletterSignupNotification from "@/emails/NewsletterSignupNotification";
import { z } from "zod";

const newsletterSchema = z.object({
  email: z.string().email(),
});

/**
 * POST /api/newsletter
 * Subscribe to newsletter
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    const validation = newsletterSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: validation.error.issues[0].message },
        { status: 400 }
      );
    }

    const { email } = validation.data;

    const newsletterStatus = await prisma.siteSettings.findUnique({
      where: { key: "newsletter_enabled" },
      select: { value: true },
    });

    const isNewsletterEnabled = newsletterStatus?.value !== "false";
    if (!isNewsletterEnabled) {
      return NextResponse.json(
        { error: "Newsletter signups are currently disabled." },
        { status: 503 }
      );
    }

    // Check if already subscribed
    const existing = await prisma.newsletterSubscriber.findUnique({
      where: { email },
    });

    if (existing) {
      if (existing.isActive) {
        return NextResponse.json(
          { message: "You're already subscribed to our newsletter!" },
          { status: 200 }
        );
      } else {
        // Reactivate subscription
        const subscriber = await prisma.newsletterSubscriber.update({
          where: { email },
          data: { isActive: true, subscribedAt: new Date() },
        });

        // Send welcome back email and admin notification
        try {
          const [emailSetting, notifySetting] = await Promise.all([
            prisma.siteSettings.findUnique({
              where: { key: "contactEmail" },
            }),
            prisma.siteSettings.findUnique({
              where: { key: "notifyAdminOnNewsletterSignup" },
            }),
          ]);
          const fromEmail = emailSetting?.value || "onboarding@resend.dev";
          const shouldNotifyAdmin = notifySetting?.value === "true";

          const welcomeBackHtml = await render(
            NewsletterWelcomeEmail({
              email,
              unsubscribeToken: subscriber.unsubscribeToken,
            }),
            { pretty: false }
          );

          await resend.emails.send({
            from: `Artisan Roast <${fromEmail}>`,
            to: [email],
            subject: "Welcome Back to Artisan Roast Newsletter! ☕",
            html: welcomeBackHtml,
          });

          // Send admin notification if enabled
          if (shouldNotifyAdmin) {
            const totalSubscribers = await prisma.newsletterSubscriber.count({
              where: { isActive: true },
            });

            const resubNotificationHtml = await render(
              NewsletterSignupNotification({
                subscriberEmail: email,
                subscribedAt: subscriber.subscribedAt.toLocaleString("en-US", {
                  dateStyle: "long",
                  timeStyle: "short",
                }),
                totalSubscribers,
              }),
              { pretty: false }
            );

            await resend.emails.send({
              from: `Artisan Roast Notifications <${fromEmail}>`,
              to: [fromEmail],
              subject: `Newsletter Resubscribed: ${email}`,
              html: resubNotificationHtml,
            });
          }
        } catch (emailError) {
          console.error("Error sending welcome back email:", emailError);
        }

        return NextResponse.json(
          { message: "Welcome back! Your subscription has been reactivated." },
          { status: 200 }
        );
      }
    }

    // Create new subscription (unsubscribeToken auto-generated by Prisma)
    const subscriber = await prisma.newsletterSubscriber.create({
      data: {
        email,
      },
    });

    // Get settings
    const [emailSetting, notifySetting] = await Promise.all([
      prisma.siteSettings.findUnique({
        where: { key: "contactEmail" },
      }),
      prisma.siteSettings.findUnique({
        where: { key: "notifyAdminOnNewsletterSignup" },
      }),
    ]);
    const fromEmail = emailSetting?.value || "onboarding@resend.dev";
    const shouldNotifyAdmin = notifySetting?.value === "true";

    // Send welcome email
    try {
      const emailHtml = await render(
        NewsletterWelcomeEmail({
          email,
          unsubscribeToken: subscriber.unsubscribeToken,
        }),
        { pretty: false }
      );

      console.log("Welcome email HTML length:", emailHtml.length);

      await resend.emails.send({
        from: `Artisan Roast <${fromEmail}>`,
        to: [email],
        subject: "Welcome to Artisan Roast Newsletter! ☕",
        html: emailHtml,
      });
    } catch (emailError) {
      console.error("Error sending welcome email:", emailError);
      // Don't fail the subscription if email fails
    }

    // Send admin notification if enabled
    if (shouldNotifyAdmin) {
      try {
        const totalSubscribers = await prisma.newsletterSubscriber.count({
          where: { isActive: true },
        });

        const notificationHtml = await render(
          NewsletterSignupNotification({
            subscriberEmail: email,
            subscribedAt: subscriber.subscribedAt.toLocaleString("en-US", {
              dateStyle: "long",
              timeStyle: "short",
            }),
            totalSubscribers,
          }),
          { pretty: false }
        );

        console.log("Admin notification HTML length:", notificationHtml.length);

        await resend.emails.send({
          from: `Artisan Roast Notifications <${fromEmail}>`,
          to: [fromEmail],
          subject: `New Newsletter Subscriber: ${email}`,
          html: notificationHtml,
        });
      } catch (adminEmailError) {
        console.error("Error sending admin notification:", adminEmailError);
        // Don't fail the subscription if admin email fails
      }
    }

    return NextResponse.json(
      { message: "Successfully subscribed to our newsletter!" },
      { status: 201 }
    );
  } catch (error) {
    console.error("Error subscribing to newsletter:", error);
    return NextResponse.json(
      { error: "Failed to subscribe. Please try again later." },
      { status: 500 }
    );
  }
}
